export enum FileErrorTypeEnum {
    FILE_ALREADY_EXIST ,
    FILE_NOT_FOUND,
    PARENT_FILE_NOT_FOUND,
    FILE_VERSION_NOT_FOUND,
    PINS_NOT_FOUND,
    FILE_NOT_ADDED ,
    PROJECT_NOT_FOUND,
    COMMENT_NOT_FOUND,
    COMMENT_ID_NOT_PROVIDE,
    COMMENT_NOT_ADDED,
    COMMENT_NOT_UPDATED,
    COMMENT_NOT_DELETED
}