

trigger:
- testsudo

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'cudodockersp'
    repository: 'mf-tinder'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'cudodockersp'
    repository: 'mf-tinder'
    command: 'push'