name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - '*'
variables:
- name: stage_dev_release
  value: false
- name: stage_uat_release
  value: true
- name: stage_test_release
  value: false

pool: cudo-selfhosted-agent

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build_Root
        steps:
          - checkout: self
            clean: false
            lfs: false
          - script: |  
                  find . -path ./node_modules -prune -false -o  -iname package.json -newermt '60 seconds ago' -exec rm -f package-lock.json \;
                  find . -path ./node_modules -prune -false -o  -iname package.json -newermt '60 seconds ago' -exec npm install \;
            displayName: 'CI for Root'
