name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - '*'
variables:
- name: stage_dev_release
  value: false
- name: stage_uat_release
  value: true
- name: stage_test_release
  value: false

pool: cudo-selfhosted-agent

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build_Root
        steps:
        - task: Cache@2
          displayName: Cache node_modules
          inputs:
            key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
            path: $(Build.SourcesDirectory)/node_modules
            cacheHitVar: CACHE_RESTORED

        - task: Npm@1
          displayName: 'Install the dependencies'
          inputs:
            command: custom
            verbose: false
            customCommand: 'ci'
            condition: ne(variables.CACHE_RESTORED, 'true')

                  #find . -path ./node_modules -prune -false -o  -iname package.json -newermt '60 seconds ago' -exec npm install \;
                  #npm install
            displayName: 'CI for Root'
