name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - '*'
variables:
- name: stage_dev_release
  value: false
- name: stage_uat_release
  value: true
- name: stage_test_release
  value: false

pool: cudo-selfhosted-agent

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build_Root
        steps:
          - task: Cache@2
            inputs:
              key: '**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json'
              path: '$(System.DefaultWorkingDirectory)/node_modules'
              displayName: 'Cache Node Modules'
          - script: npm install 
                  #find . -path ./node_modules -prune -false -o  -iname package.json -newermt '60 seconds ago' -exec npm install \;
                  #npm install
            displayName: 'CI for Root'
