name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

trigger:
  branches:
    include:
      - dev
      - test
      - uat

  paths:
    exclude:
      - '*'
    include:
      - 'package.json'

variables:
- name: stage_dev_release
  value: false
- name: stage_uat_release
  value: true
- name: stage_test_release
  value: false

pool: dbc-selfhosted

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build_Root
        steps:
          - script: |
              npm install
            displayName: 'CI for Root'
