apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfdocument
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mfdocument
  template:
    metadata:
      labels:
        app: mfdocument
    spec:
      containers:
      - name: mfdocument
        image: cudoacr.azurecr.io/mfdocument:v1
        ports:
        - containerPort: 6010
      imagePullSecrets:
      - name: acr-auth
