# Use Node.js LTS version with Alpine Linux as a base image
FROM node:lts-alpine3.16

WORKDIR /usr/src/app

COPY package*.json ./
COPY /apps/ms-account/project.json ./
COPY cypress*.json ./

# Install Python3 and create a symlink to `python`
RUN apk update \
&& apk add --no-cache python3 build-base \
&& ln -s /usr/bin/python3 /usr/bin/python



RUN npm install
RUN npm install -g nx

COPY . .
EXPOSE 5001

CMD ["nx", "serve", "ms-account", "--host", "0.0.0.0"]
