FROM node:lts

WORKDIR /usr/src/app

COPY package*.json ./
COPY workspace*.json ./
COPY cypress*.json ./

RUN apt-get update \
&& apt-get install -y python3 \
&& ln -s /usr/bin/python3 /usr/bin/python


RUN npm install
RUN npm install -g nx


COPY . .
#RUN npm run build ms-tender
#CMD ["node", "dist/main"]
#RUN nohup npm start ms-tender > stdout.txt 2> stderr.txt &
EXPOSE 5007

ENV HOST 0.0.0.0
CMD ["nx", "serve","ms-tender"]
