FROM node:lts

WORKDIR /usr/src/app

COPY package*.json ./
COPY workspace*.json ./
COPY cypress*.json ./


RUN npm install
RUN npm install -g nx

COPY . .
EXPOSE 5001

ENV HOST 0.0.0.0
CMD ["nx", "serve","ms-account"]
