FROM node:14.15-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY workspace*.json ./
COPY cypress*.json ./
RUN npm install
COPY . .
#RUN npm run build ms-project
#CMD ["node", "dist/main"]
#RUN nohup npm start ms-project > stdout.txt 2> stderr.txt &
EXPOSE 5005
CMD ["npm", "start","ms-project"]
