FROM node:14.15-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY workspace*.json ./
COPY cypress*.json ./
RUN npm install
COPY . .
#RUN npm run build ms-task
#CMD ["node", "dist/main"]
#RUN nohup npm start ms-task > stdout.txt 2> stderr.txt &
EXPOSE 5007
CMD ["npm", "run","nx","serve","mf-project-app","--host0.0.0.0"]

