FROM node:lts

WORKDIR /usr/src/app

COPY package*.json ./
COPY workspace*.json ./
COPY cypress*.json ./

RUN npm install
RUN npm install -g nx

COPY . .
#RUN npm run build ms-task
#CMD ["node", "dist/main"]
#RUN nohup npm start ms-task > stdout.txt 2> stderr.txt &
EXPOSE 5007

CMD ["npm", "run","nx","serve","mf-container-app","--host0.0.0.0"]
