# Use Node.js LTS version with Alpine Linux as a base image
FROM node:lts-alpine3.16

# Set the working directory for the app
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Copy workspace.json and cypress.json
COPY /apps/ms-task/project.json ./
COPY cypress*.json ./

# Install Python3 and create a symlink to `python`
RUN apk update \
&& apk add --no-cache python3 build-base \
&& ln -s /usr/bin/python3 /usr/bin/python


# Install npm dependencies
RUN npm ci

# Install Nx CLI globally
RUN npm install -g nx

# Copy the rest of the application files
COPY . .

EXPOSE 5007

CMD ["nx","serve","ms-task","--host", "0.0.0.0"]
