FROM nginx:1.15.2-alpine
COPY ./dist/apps/mf-container-app/ /usr/share/nginx/html
COPY ./deploy/docker-compose-frontend/nginx_mf-container.conf  /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]