# Use Node.js LTS version with Alpine Linux as a base image
FROM node:lts-alpine3.16

WORKDIR /usr/src/app

COPY package*.json ./
COPY workspace*.json ./
COPY cypress*.json ./

RUN npm install
RUN npm install -g nx

COPY . .
#RUN npm run build ms-task
#CMD ["node", "dist/main"]
#RUN nohup npm start ms-task > stdout.txt 2> stderr.txt &
EXPOSE 5007

CMD ["npm", "run","nx","serve","mf-document-app","--host0.0.0.0"]

