module.exports = {
  projects: [
    '<rootDir>/apps/mf-container-app',
    '<rootDir>/apps/mf-account-app',
    '<rootDir>/apps/ms-account',
    '<rootDir>/apps/mf-project-app',
    '<rootDir>/apps/ms-project',
    '<rootDir>/libs/ui',
    '<rootDir>/libs/shared',
    '<rootDir>/libs/data',
    '<rootDir>/apps/ms-task',
    '<rootDir>/apps/ms-tender',
    '<rootDir>/apps/ms-cost',
    '<rootDir>/apps/ms-meeting',
    '<rootDir>/apps/ms-document',
    '<rootDir>/apps/ms-protocol',
    '<rootDir>/apps/mf-task-app',
    '<rootDir>/apps/mf-tender-app',
    '<rootDir>/apps/mf-cost-app',
    '<rootDir>/apps/mf-meeting-app',
    '<rootDir>/libs/interfaces',
    '<rootDir>/libs/data-access',
    '<rootDir>/libs/ms-core',
    '<rootDir>/libs/shared-components',
  ],
};
