apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: message-topic
spec:
  type: bindings.kafka
  metadata:
    # Kafka broker connection setting
    - name: brokers
      value: dapr-kafka.kafka:9092
    # consumer configuration: topic and consumer group
    - name: topics
      value: message
    - name: consumerGroup
      value: group1
    # publisher configuration: topic
    - name: publishTopic
      value: message
    - name: authRequired
      value: "false"
