kind: Service
apiVersion: v1
metadata:
  name: ms-account
  labels:
    app: ms-account
spec:
  selector:
    app: ms-account
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-account
  labels:
    app: ms-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-account
  template:
    metadata:
      labels:
        app: ms-account
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ms-account"
        dapr.io/app-port: "3000"
    spec:
      containers:
        - name: node
          image: 192.168.0.31:5000/ms-account
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
