version: "3.7"

services:
  kratos-migrate:
    image: oryd/kratos:v0.5.5-alpha.1
    environment:
      - DSN=mysql://cudo:Welcome@1@tcp(112.196.20.249:3306)/cudo?max_conns=20&max_idle_conns=4
    volumes:
     # - type: volume
        #source: kratos-mysql
        #target: /var/lib/mysql
      #  read_only: false
      - type: bind
        source: ./.kratos-config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    #networks:
      #- intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.5.5-alpha.1
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=mysql://cudo:Welcome@1@tcp(112.196.20.249:3306)/cudo?max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev
    volumes:
     # - type: volume
        #source: kratos-mysql
        #target: /var/lib/mysql
      #  read_only: false
      - type: bind
        source: ./.kratos-config
        target: /etc/config/kratos
   # networks:
     # - intranet

        #  mailslurper:
        #    image: oryd/mailslurper:latest-smtps
        #    ports:
        #      - "4436:4436"
        #      - "4437:4437"
    #networks:
     # - intranet

