export enum TaskErrorTypeEnum {
    RECORD_ALREADY_EXIST ,
    RECORD_NOT_EXIST ,
    RECORD_NOT_ADDED ,
    PROJECT_NOT_FOUND,
    NO_REFERANCE_TYPE,
    NO_TITLE,
    NO_ASSIGNEE,
    NO_WORKTYPE,
    NO_PHASE,
    WRONG_DATE,
    NO_DATE,    
    INTERNAL_SERVER_ERROR
}