name: $(Date:yyyyMMdd).$(Rev:r).$(Build.BuildId)

trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - 'apps/ms-account/*'
    exclude:
      - '*'
variables:
- name: stage_dev_release
  value: false
- name: stage_uat_release
  value: true
- name: stage_test_release
  value: false
- name: imageRepository
  value: 

pool: cudo-selfhosted-agent

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build_Root
        steps:
          - checkout: self
            clean: false
            lfs: false
            #           path: abc
          - bash : |
                  cp docker/ms-dockerfile apps/ms-account/Dockerfile
                  find . -path ./node_modules -prune -false -o  -iname package.json -newermt '60 seconds ago' -exec rm -f package-lock.json \;
                  find . -path ./node_modules -prune -false -o  -iname package.json -newermt '60 seconds ago' -exec npm install \;
                  npm run nx run-many -- --target=build --projects='ms-account' --with-deps --generatePackageJson=true
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: ms-account-dev
              dockerfile: apps/ms-account/Dockerfile
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
            displayName: 'CI for Root'
  
