FROM node:lts

WORKDIR /usr/src/app

COPY package*.json ./
COPY workspace*.json ./
COPY cypress*.json ./


RUN npm install
RUN npm install -g nx

COPY . .
EXPOSE 5001

CMD ["nx", "serve", "ms-account", "--host", "0.0.0.0"]
# CMD ["npm", "start","ms-account"]
# CMD ["npm", "run","nx","serve","ms-account","--host0.0.0.0"]
