version: '3.7'

services:
  mysqld:
    image: mysql:5.7
    ports:
      - '3309:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - kratos-mysql:/var/lib/mysql
    networks:
      - intranet
networks:
  intranet:

volumes:
  kratos-mysql:
