apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-nginx
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.env }}-nginx

