apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.env }}-nginx
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.env }}-nginx
            port:
              number: {{ .Values.service.port }}
