apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-php
spec:
  selector:
    app: {{ .Values.env }}-php
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.phpport }}

