export enum ProjectErrorTypeEnum {
    RECORD_ALREADY_EXIST,
    PROJECT_NOT_EXIST,
    COMPANY_NOT_FOUND,
    BUILDING_NOT_FOUND,
    RECORD_NOT_ADDED,
    PROJECT_NOT_FOUND,
    NO_REFERANCE_TYPE,
    NO_PROJECT_NAME,
    NO_PROJECT_NUMBER,
    NO_BUILDING,
    NO_CLIENT,
    INTERNAL_SERVER_ERROR
}